export const data = {
  data: [
    {
      keyword: "black car",
      id: 604330,
      countryCode: "us",
      updateDate: "2020-07-18T19:56:09.358267+00:00",
      updateDateIpad: "2020-07-18T19:56:09.420297+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 840,
      users_per_day: 54,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 183,
      searchads_popularity: 9,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "black car",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "cab",
      id: 231069,
      countryCode: "us",
      updateDate: "2020-07-18T17:44:32.843959+00:00",
      updateDateIpad: "2020-07-18T17:44:32.887031+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 10,
        change: 0,
      },
      total_apps: 5331,
      users_per_day: 164,
      ipad_position_info: {
        position: 9,
        change: 0,
      },
      ipad_total_apps: 2487,
      searchads_popularity: 32,
      suggestions_count: 12,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "cab",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 6,
      ipad_best_rank: 1,
    },
    {
      keyword: "cab app",
      id: 604298,
      countryCode: "us",
      updateDate: "2020-07-18T10:46:26.065100+00:00",
      updateDateIpad: "2020-07-18T10:46:26.122387+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 8,
        change: 0,
      },
      total_apps: 5333,
      users_per_day: 121,
      ipad_position_info: {
        position: 2,
        change: 0,
      },
      ipad_total_apps: 2486,
      searchads_popularity: 12,
      suggestions_count: 5,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "cab app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 4,
      ipad_best_rank: 1,
    },
    {
      keyword: "call taxi",
      id: 2590052,
      countryCode: "us",
      updateDate: "2020-07-18T02:21:50.468254+00:00",
      updateDateIpad: "2020-07-18T02:21:50.477292+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 9,
        change: 0,
      },
      total_apps: 285,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 163,
      searchads_popularity: 5,
      suggestions_count: 6,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "call taxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 1,
      ipad_best_rank: 1,
    },
    {
      keyword: "gett",
      id: 231076,
      countryCode: "us",
      updateDate: "2020-07-18T11:48:58.156193+00:00",
      updateDateIpad: "2020-07-18T11:48:58.284520+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 11,
        change: 0,
      },
      total_apps: 25,
      users_per_day: 143,
      ipad_position_info: {
        position: 2,
        change: 0,
      },
      ipad_total_apps: 15,
      searchads_popularity: 27,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "given",
      translation_from: "sv",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 1,
    },
    {
      keyword: "gettaxi",
      id: 2403914,
      countryCode: "us",
      updateDate: "2020-07-18T02:39:07.924841+00:00",
      updateDateIpad: "2020-07-18T02:39:07.949790+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 2,
        change: 0,
      },
      total_apps: 222,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 96,
      searchads_popularity: 7,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "gettaxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "go home",
      id: 2590069,
      countryCode: "us",
      updateDate: "2020-07-18T08:02:23.506887+00:00",
      updateDateIpad: "2020-07-18T08:02:23.570617+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 29508,
      users_per_day: 121,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 18856,
      searchads_popularity: 22,
      suggestions_count: 10,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "go home",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "grab car",
      id: 2384680,
      countryCode: "us",
      updateDate: "2020-07-18T13:52:41.296496+00:00",
      updateDateIpad: "2020-07-18T13:52:41.330608+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 4,
        change: 0,
      },
      total_apps: 1050,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 710,
      searchads_popularity: 5,
      suggestions_count: 2,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "grab car",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 1,
    },
    {
      keyword: "grabtaxi",
      id: 2393286,
      countryCode: "us",
      updateDate: "2020-07-18T09:17:32.924214+00:00",
      updateDateIpad: "2020-07-18T09:17:32.971781+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 5,
        change: 0,
      },
      total_apps: 1080,
      users_per_day: 121,
      ipad_position_info: {
        position: 7,
        change: 0,
      },
      ipad_total_apps: 726,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "grabtaxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 4,
      ipad_best_rank: 1,
    },
    {
      keyword: "grab taxi",
      id: 604340,
      countryCode: "us",
      updateDate: "2020-07-18T12:48:32.922067+00:00",
      updateDateIpad: "2020-07-18T12:48:32.951735+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 5,
        change: 0,
      },
      total_apps: 1089,
      users_per_day: 67,
      ipad_position_info: {
        position: 4,
        change: 0,
      },
      ipad_total_apps: 728,
      searchads_popularity: 21,
      suggestions_count: 2,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "grab taxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 1,
    },
    {
      keyword: "local taxi",
      id: 2590071,
      countryCode: "us",
      updateDate: "2020-07-18T06:47:20.277189+00:00",
      updateDateIpad: "2020-07-18T06:47:20.298494+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 4,
        change: 0,
      },
      total_apps: 23145,
      users_per_day: 0,
      ipad_position_info: {
        position: 2,
        change: 0,
      },
      ipad_total_apps: 14862,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "local taxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 2,
    },
    {
      keyword: "lyft",
      id: 2518600,
      countryCode: "us",
      updateDate: "2020-07-18T06:55:50.217731+00:00",
      updateDateIpad: "2020-07-18T06:55:50.236551+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 3,
        change: 0,
      },
      total_apps: 54,
      users_per_day: 17895,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 29,
      searchads_popularity: 76,
      suggestions_count: 12,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "lift",
      translation_from: "sv",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 1,
    },
    {
      keyword: "lyft app",
      id: 2518786,
      countryCode: "us",
      updateDate: "2020-07-18T03:46:59.140084+00:00",
      updateDateIpad: "2020-07-18T03:46:59.153909+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 2,
        change: 0,
      },
      total_apps: 51,
      users_per_day: 205,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 24,
      searchads_popularity: 29,
      suggestions_count: 3,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "lifting ideas",
      translation_from: "sv",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "new york",
      id: 477298,
      countryCode: "us",
      updateDate: "2020-07-18T17:30:28.601893+00:00",
      updateDateIpad: "2020-07-18T17:30:28.646429+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 4968,
      users_per_day: 159,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 3258,
      searchads_popularity: 29,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "new york",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "nyc taxi app",
      id: 2590048,
      countryCode: "us",
      updateDate: "2020-07-18T07:17:34.484173+00:00",
      updateDateIpad: "2020-07-18T07:17:34.505570+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 49,
      users_per_day: 62,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 33,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "nyc taxi app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "ny taxi",
      id: 603722,
      countryCode: "us",
      updateDate: "2020-07-18T01:45:08.907037+00:00",
      updateDateIpad: "2020-07-18T01:45:08.953335+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 5,
        change: 0,
      },
      total_apps: 23131,
      users_per_day: 43,
      ipad_position_info: {
        position: 2,
        change: 0,
      },
      ipad_total_apps: 14860,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "the taxi",
      translation_from: "mg",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 2,
    },
    {
      keyword: "ride",
      id: 604296,
      countryCode: "us",
      updateDate: "2020-07-18T03:40:45.213402+00:00",
      updateDateIpad: "2020-07-18T03:40:45.241405+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 11,
        change: 0,
      },
      total_apps: 11556,
      users_per_day: 226,
      ipad_position_info: {
        position: 36,
        change: 0,
      },
      ipad_total_apps: 7507,
      searchads_popularity: 40,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "ride",
      translation_from: "en",
      in_name: {
        count: 1,
        full: true,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 7,
      ipad_best_rank: 3,
    },
    {
      keyword: "rideshare",
      id: 2353052,
      countryCode: "us",
      updateDate: "2020-07-18T10:16:10.525406+00:00",
      updateDateIpad: "2020-07-18T10:16:10.537493+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 9,
        change: 0,
      },
      total_apps: 1269,
      users_per_day: 164,
      ipad_position_info: {
        position: 2,
        change: 0,
      },
      ipad_total_apps: 496,
      searchads_popularity: 32,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "rideshare",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 5,
      ipad_best_rank: 1,
    },
    {
      keyword: "ridesharing",
      id: 230720,
      countryCode: "us",
      updateDate: "2020-07-18T09:26:31.984842+00:00",
      updateDateIpad: "2020-07-18T09:26:32.037110+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 244,
      users_per_day: 0,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 76,
      searchads_popularity: 5,
      suggestions_count: 10,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "ridesharing",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "share",
      id: 477904,
      countryCode: "us",
      updateDate: "2020-07-18T21:21:57.063275+00:00",
      updateDateIpad: "2020-07-18T21:21:57.307211+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 61,
        change: 0,
      },
      total_apps: 18441,
      users_per_day: 216,
      ipad_position_info: {
        position: 51,
        change: 0,
      },
      ipad_total_apps: 10184,
      searchads_popularity: 39,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "share",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 10,
      ipad_best_rank: 4,
    },
    {
      keyword: "share taxi",
      id: 2590057,
      countryCode: "us",
      updateDate: "2020-07-18T11:38:54.712747+00:00",
      updateDateIpad: "2020-07-18T11:38:54.732744+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 1,
        change: 0,
      },
      total_apps: 445,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 158,
      searchads_popularity: 5,
      suggestions_count: 3,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "share taxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 1,
      ipad_best_rank: 1,
    },
    {
      keyword: "sharing",
      id: 482662,
      countryCode: "us",
      updateDate: "2020-07-18T04:32:16.684845+00:00",
      updateDateIpad: "2020-07-18T04:32:16.713876+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 42,
        change: 0,
      },
      total_apps: 17897,
      users_per_day: 110,
      ipad_position_info: {
        position: 17,
        change: 0,
      },
      ipad_total_apps: 9831,
      searchads_popularity: 20,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "sharing",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 15,
      ipad_best_rank: 16,
    },
    {
      keyword: "sidecar",
      id: 2357078,
      countryCode: "us",
      updateDate: "2020-07-18T11:53:56.162693+00:00",
      updateDateIpad: "2020-07-18T11:53:56.193706+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 26,
        change: 0,
      },
      total_apps: 722,
      users_per_day: 210,
      ipad_position_info: {
        position: 9,
        change: 0,
      },
      ipad_total_apps: 237,
      searchads_popularity: 38,
      suggestions_count: 4,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "sidecar",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "siri",
      id: 194,
      countryCode: "us",
      updateDate: "2020-07-18T09:48:25.672311+00:00",
      updateDateIpad: "2020-07-18T09:48:25.700190+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 15,
        change: 0,
      },
      total_apps: 1356,
      users_per_day: 993,
      ipad_position_info: {
        position: 15,
        change: 0,
      },
      ipad_total_apps: 794,
      searchads_popularity: 48,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "siri",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 2,
    },
    {
      keyword: "taxi",
      id: 226921,
      countryCode: "us",
      updateDate: "2020-07-18T12:09:42.652206+00:00",
      updateDateIpad: "2020-07-18T12:09:42.803604+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 16,
        change: 0,
      },
      total_apps: 23690,
      users_per_day: 477,
      ipad_position_info: {
        position: 48,
        change: 0,
      },
      ipad_total_apps: 15166,
      searchads_popularity: 44,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxi",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 11,
      ipad_best_rank: 11,
    },
    {
      keyword: "taxi app",
      id: 604272,
      countryCode: "us",
      updateDate: "2020-07-18T05:16:00.377532+00:00",
      updateDateIpad: "2020-07-18T05:16:00.442503+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 8,
        change: 0,
      },
      total_apps: 23641,
      users_per_day: 83,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 15129,
      searchads_popularity: 22,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxi app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 1,
    },
    {
      keyword: "taxi apps",
      id: 603154,
      countryCode: "us",
      updateDate: "2020-07-18T07:20:25.012052+00:00",
      updateDateIpad: "2020-07-18T07:20:25.077789+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 9,
        change: 0,
      },
      total_apps: 23651,
      users_per_day: 54,
      ipad_position_info: {
        position: 9,
        change: 0,
      },
      ipad_total_apps: 15135,
      searchads_popularity: 14,
      suggestions_count: 3,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxi apps",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 2,
    },
    {
      keyword: "taxi cab app",
      id: 604270,
      countryCode: "us",
      updateDate: "2020-07-18T07:53:37.743565+00:00",
      updateDateIpad: "2020-07-18T07:53:37.832415+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 6,
        change: 0,
      },
      total_apps: 5739,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 3182,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxi cab app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "taxis",
      id: 604300,
      countryCode: "us",
      updateDate: "2020-07-18T01:45:51.453451+00:00",
      updateDateIpad: "2020-07-18T01:45:51.564482+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 9,
        change: 0,
      },
      total_apps: 24016,
      users_per_day: 99,
      ipad_position_info: {
        position: 39,
        change: 0,
      },
      ipad_total_apps: 15299,
      searchads_popularity: 17,
      suggestions_count: 12,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxis",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 3,
    },
    {
      keyword: "taxi service",
      id: 2590075,
      countryCode: "us",
      updateDate: "2020-07-18T15:40:32.842644+00:00",
      updateDateIpad: "2020-07-18T15:40:32.868677+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 6,
        change: 0,
      },
      total_apps: 23132,
      users_per_day: 54,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 14864,
      searchads_popularity: 12,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "taxi service",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "transit app",
      id: 2395832,
      countryCode: "us",
      updateDate: "2020-07-18T03:54:08.247659+00:00",
      updateDateIpad: "2020-07-18T03:54:08.282134+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: "-",
        change: null,
      },
      total_apps: 2591,
      users_per_day: 156,
      ipad_position_info: {
        position: "-",
        change: null,
      },
      ipad_total_apps: 1726,
      searchads_popularity: 30,
      suggestions_count: 12,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "transit app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber",
      id: 230726,
      countryCode: "us",
      updateDate: "2020-07-18T04:28:05.686776+00:00",
      updateDateIpad: "2020-07-18T04:28:05.706409+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 1,
        change: 0,
      },
      total_apps: 237,
      users_per_day: 24267,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 210,
      searchads_popularity: 79,
      suggestions_count: 13,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "uber",
      translation_from: "en",
      in_name: {
        count: 1,
        full: true,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 1,
      ipad_best_rank: 1,
    },
    {
      keyword: "uber app",
      id: 603714,
      countryCode: "us",
      updateDate: "2020-07-18T06:56:10.720624+00:00",
      updateDateIpad: "2020-07-18T06:56:10.778297+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 1,
        change: 0,
      },
      total_apps: 5577,
      users_per_day: 210,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 3445,
      searchads_popularity: 39,
      suggestions_count: 5,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "uber app",
      translation_from: "de",
      in_name: {
        count: 1,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 1,
      ipad_best_rank: 1,
    },
    {
      keyword: "uber app free",
      id: 606214,
      countryCode: "us",
      updateDate: "2020-07-18T04:07:34.113536+00:00",
      updateDateIpad: "2020-07-18T04:07:34.140272+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 1,
        change: 0,
      },
      total_apps: 220,
      users_per_day: 89,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 116,
      searchads_popularity: 22,
      suggestions_count: 1,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "uber app free",
      translation_from: "en",
      in_name: {
        count: 1,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 1,
      ipad_best_rank: 1,
    },
    {
      keyword: "uber driver app",
      id: 2501732,
      countryCode: "us",
      updateDate: "2020-07-18T08:56:28.092373+00:00",
      updateDateIpad: "2020-07-18T08:56:28.109459+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 2,
        change: 0,
      },
      total_apps: 236,
      users_per_day: 6628,
      ipad_position_info: {
        position: 3,
        change: 0,
      },
      ipad_total_apps: 199,
      searchads_popularity: 65,
      suggestions_count: 2,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "uber driver app",
      translation_from: "en",
      in_name: {
        count: 1,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 2,
    },
    {
      keyword: "ubereats",
      id: 604938,
      countryCode: "us",
      updateDate: "2020-07-18T04:27:19.975940+00:00",
      updateDateIpad: "2020-07-18T04:27:20.007451+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 16,
        change: 0,
      },
      total_apps: 570,
      users_per_day: 1638,
      ipad_position_info: {
        position: 7,
        change: 0,
      },
      ipad_total_apps: 295,
      searchads_popularity: 51,
      suggestions_count: 4,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "ubereats",
      translation_from: "ca",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 3,
    },
    {
      keyword: "uber eats",
      id: 603716,
      countryCode: "us",
      updateDate: "2020-07-18T12:11:13.163714+00:00",
      updateDateIpad: "2020-07-18T12:11:13.185155+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 7,
        change: 0,
      },
      total_apps: 576,
      users_per_day: 24289,
      ipad_position_info: {
        position: 5,
        change: 0,
      },
      ipad_total_apps: 300,
      searchads_popularity: 78,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "uber eats",
      translation_from: "en",
      in_name: {
        count: 1,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 3,
    },
    {
      keyword: "yellow cab",
      id: 606220,
      countryCode: "us",
      updateDate: "2020-07-18T18:33:51.246254+00:00",
      updateDateIpad: "2020-07-18T18:33:51.254689+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 4,
        change: 0,
      },
      total_apps: 174,
      users_per_day: 153,
      ipad_position_info: {
        position: 7,
        change: 0,
      },
      ipad_total_apps: 145,
      searchads_popularity: 31,
      suggestions_count: 11,
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "yellow cab",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 3,
      ipad_best_rank: 2,
    },
    {
      keyword: "yellow cab app",
      id: 2501734,
      countryCode: "us",
      updateDate: "2020-07-18T06:04:22.046872+00:00",
      updateDateIpad: "2020-07-18T06:04:22.095253+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 7,
        change: 0,
      },
      total_apps: 174,
      users_per_day: 67,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 146,
      searchads_popularity: 9,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "yellow cab app",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "yellow cab austin",
      id: 2501740,
      countryCode: "us",
      updateDate: "2020-07-18T11:20:11.137423+00:00",
      updateDateIpad: "2020-07-18T11:20:11.163587+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 4,
        change: 0,
      },
      total_apps: 165,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 135,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "yellow cab austin",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
    {
      keyword: "yellow cab nyc",
      id: 2501738,
      countryCode: "us",
      updateDate: "2020-07-18T05:57:17.526257+00:00",
      updateDateIpad: "2020-07-18T05:57:17.548455+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 10,
        change: 0,
      },
      total_apps: 187,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 149,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "yellow cab nyc",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 5,
      ipad_best_rank: 1,
    },
    {
      keyword: "yellow cab of dc",
      id: 2501750,
      countryCode: "us",
      updateDate: "2020-07-18T03:03:10.618362+00:00",
      updateDateIpad: "2020-07-18T03:03:10.679632+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: {
        position: 2,
        change: 0,
      },
      total_apps: 165,
      users_per_day: 0,
      ipad_position_info: {
        position: 1,
        change: 0,
      },
      ipad_total_apps: 135,
      searchads_popularity: 5,
      suggestions_count: [],
      timestamp: "-",
      _timestamp: null,
      color: 0,
      translation: "yellow cab of dc",
      translation_from: "en",
      in_name: {
        count: 0,
        full: false,
      },
      in_subtitle: {
        count: 0,
        full: false,
      },
      best_rank: 2,
      ipad_best_rank: 1,
    },
  ],
};
